services:
  main-app:
    container_name: main-app
    build: ..
    command: 'python app/application/bot/main.py'
    volumes:
      - ../app/:/app
    env_file:
      - ../.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
